// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF7bvtEKpbxu4TEPslbRKkhJ3jarYirxQ',
    appId: '1:860326809902:web:21027ff8b574a10eebeabf',
    messagingSenderId: '860326809902',
    projectId: 'flutter-app-798b5',
    authDomain: 'flutter-app-798b5.firebaseapp.com',
    databaseURL: 'https://flutter-app-798b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-798b5.firebasestorage.app',
    measurementId: 'G-9ZYSH2NE69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJqIqAGu2c7riisvFpdW_bxPIJn8WxYs',
    appId: '1:860326809902:android:2c246874f905b413ebeabf',
    messagingSenderId: '860326809902',
    projectId: 'flutter-app-798b5',
    databaseURL: 'https://flutter-app-798b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-798b5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrG80CWXsufPXiGk9v2kWXJFoS-w5e66g',
    appId: '1:860326809902:web:b96a2a0f0a756ef3ebeabf',
    messagingSenderId: '860326809902',
    projectId: 'flutter-app-798b5',
    authDomain: 'flutter-app-798b5.firebaseapp.com',
    databaseURL: 'https://flutter-app-798b5-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-798b5.firebasestorage.app',
    measurementId: 'G-P7FX7LBTCT',
  );
}
